"""
services/report_generator.py
Generate PDF and DOCX reports from meeting MoM markdown.
"""
from __future__ import annotations

import io
import re
from datetime import datetime

import structlog

log = structlog.get_logger(__name__)


# ═══════════════════════════════════════════════════════════════
# PDF via ReportLab
# ═══════════════════════════════════════════════════════════════

def generate_pdf_mom(title: str, mom_markdown: str, created_at: datetime | None = None) -> bytes:
    """
    Render the MoM markdown to a clean PDF using ReportLab.
    Returns raw PDF bytes.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    # Custom styles
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], fontSize=18, spaceAfter=8, textColor=colors.HexColor("#4c1d95"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13, spaceAfter=6, textColor=colors.HexColor("#5b21b6"))
    h3 = ParagraphStyle("H3", parent=styles["Heading3"], fontSize=11, spaceAfter=4, textColor=colors.HexColor("#6d28d9"))
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=15, spaceAfter=4)
    bullet = ParagraphStyle("Bullet", parent=body, leftIndent=20, bulletIndent=10, spaceAfter=2)
    meta = ParagraphStyle("Meta", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#6b7280"))

    story = []

    # Header
    story.append(Paragraph("MeetingMind AI", ParagraphStyle("Brand", parent=styles["Normal"],
        fontSize=10, textColor=colors.HexColor("#7c3aed"), spaceAfter=2)))
    story.append(Paragraph("Minutes of Meeting", h1))
    if created_at:
        story.append(Paragraph(f"Generated: {created_at.strftime('%B %d, %Y')}", meta))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#7c3aed"), spaceAfter=12))

    # Parse markdown into ReportLab flowables
    lines = mom_markdown.split("\n")
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            story.append(Spacer(1, 6))
            continue
        if line_stripped.startswith("# "):
            story.append(Paragraph(line_stripped[2:], h1))
        elif line_stripped.startswith("## "):
            story.append(Spacer(1, 8))
            story.append(Paragraph(line_stripped[3:], h2))
        elif line_stripped.startswith("### "):
            story.append(Paragraph(line_stripped[4:], h3))
        elif line_stripped.startswith(("- ", "* ")):
            text = _md_inline(line_stripped[2:])
            story.append(Paragraph(f"• {text}", bullet))
        elif re.match(r"^\d+\.", line_stripped):
            text = _md_inline(re.sub(r"^\d+\.\s*", "", line_stripped))
            story.append(Paragraph(text, bullet))
        elif line_stripped.startswith("|"):
            # Skip markdown tables (complex — handle inline as text)
            story.append(Paragraph(_md_inline(line_stripped.replace("|", " | ")), body))
        elif line_stripped.startswith("---"):
            story.append(HRFlowable(width="100%", thickness=0.5,
                color=colors.HexColor("#e5e7eb"), spaceBefore=4, spaceAfter=4))
        else:
            story.append(Paragraph(_md_inline(line_stripped), body))

    # Footer spacer
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        f"Generated by MeetingMind AI · {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC",
        ParagraphStyle("Footer", parent=meta, alignment=1)
    ))

    doc.build(story)
    return buf.getvalue()


def _md_inline(text: str) -> str:
    """Convert inline markdown (bold, italic) to ReportLab XML tags."""
    # Bold: **text** → <b>text</b>
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Italic: *text* → <i>text</i>
    text = re.sub(r"\*(.+?)\*", r"<i>\1</i>", text)
    # Code: `text` → <font name="Courier">text</font>
    text = re.sub(r"`(.+?)`", r'<font name="Courier">\1</font>', text)
    return text


# ═══════════════════════════════════════════════════════════════
# DOCX via python-docx
# ═══════════════════════════════════════════════════════════════

def generate_docx_mom(title: str, mom_markdown: str) -> bytes:
    """
    Render MoM markdown to a .docx document.
    Returns raw DOCX bytes.
    """
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Page margins
    section = doc.sections[0]
    section.left_margin = section.right_margin = int(2.5 * 914400 / 2.54)   # ~2.5cm in EMU

    # Brand header
    brand_para = doc.add_paragraph()
    brand_run = brand_para.add_run("MeetingMind AI")
    brand_run.font.color.rgb = RGBColor(0x7C, 0x3A, 0xED)
    brand_run.font.size = Pt(10)
    brand_run.bold = True

    lines = mom_markdown.split("\n")
    for line in lines:
        line_stripped = line.strip()
        if not line_stripped:
            doc.add_paragraph()
            continue
        if line_stripped.startswith("# "):
            p = doc.add_heading(line_stripped[2:], level=1)
            p.runs[0].font.color.rgb = RGBColor(0x4C, 0x1D, 0x95)
        elif line_stripped.startswith("## "):
            p = doc.add_heading(line_stripped[3:], level=2)
        elif line_stripped.startswith("### "):
            doc.add_heading(line_stripped[4:], level=3)
        elif line_stripped.startswith(("- ", "* ")):
            doc.add_paragraph(line_stripped[2:], style="List Bullet")
        elif re.match(r"^\d+\.", line_stripped):
            doc.add_paragraph(
                re.sub(r"^\d+\.\s*", "", line_stripped),
                style="List Number"
            )
        elif line_stripped.startswith("---"):
            p = doc.add_paragraph("─" * 60)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        elif line_stripped.startswith("|"):
            doc.add_paragraph(line_stripped.replace("|", "\t"))
        else:
            # Strip inline markdown for docx
            clean = re.sub(r"\*\*(.+?)\*\*", r"\1", line_stripped)
            clean = re.sub(r"\*(.+?)\*", r"\1", clean)
            doc.add_paragraph(clean)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
